In [1]:
import pandas as pd

# Farm data dictionary
farm_data = {
    "Crop": ["Wheat", "Rice", "Maize", "Millet"],
    "Yield_kg": [3200, 2800, 3500, 3000],
    "Water_liters": [4200, 5500, 3800, 3000],
    "Cost_INR": [18000, 20000, 17000, 15000]
}

# Create DataFrame
df = pd.DataFrame(farm_data)
df

     Crop  Yield_kg  Water_liters  Cost_INR
0   Wheat      3200          4200     18000
1    Rice      2800          5500     20000
2   Maize      3500          3800     17000
3  Millet      3000          3000     15000

In [2]:
df[["Crop", "Yield_kg"]]

     Crop  Yield_kg
0   Wheat      3200
1    Rice      2800
2   Maize      3500
3  Millet      3000

In [3]:
df["Revenue_INR"] = df["Yield_kg"] * 20
df

     Crop  Yield_kg  Water_liters  Cost_INR  Revenue_INR
0   Wheat      3200          4200     18000        64000
1    Rice      2800          5500     20000        56000
2   Maize      3500          3800     17000        70000
3  Millet      3000          3000     15000        60000

In [4]:
df["Revenue_INR"] = df["Yield_kg"] * 20
df

     Crop  Yield_kg  Water_liters  Cost_INR  Revenue_INR
0   Wheat      3200          4200     18000        64000
1    Rice      2800          5500     20000        56000
2   Maize      3500          3800     17000        70000
3  Millet      3000          3000     15000        60000

In [5]:
df[df["Yield_kg"] > 3000]

    Crop  Yield_kg  Water_liters  Cost_INR  Revenue_INR
0  Wheat      3200          4200     18000        64000
2  Maize      3500          3800     17000        70000

In [6]:
df.sort_values(by="Yield_kg", ascending=False)

     Crop  Yield_kg  Water_liters  Cost_INR  Revenue_INR
2   Maize      3500          3800     17000        70000
0   Wheat      3200          4200     18000        64000
3  Millet      3000          3000     15000        60000
1    Rice      2800          5500     20000        56000

In [7]:
df.sort_values(by="Yield_kg", ascending=False)

     Crop  Yield_kg  Water_liters  Cost_INR  Revenue_INR
2   Maize      3500          3800     17000        70000
0   Wheat      3200          4200     18000        64000
3  Millet      3000          3000     15000        60000
1    Rice      2800          5500     20000        56000

In [8]:
df["Yield_kg"].mean()

np.float64(3125.0)

In [9]:
df["Yield_kg"].max()

3500

In [10]:
df["Yield_kg"].min()

2800

In [11]:
df["Cost_per_kg"] = df["Cost_INR"] / df["Yield_kg"]
df

     Crop  Yield_kg  Water_liters  Cost_INR  Revenue_INR  Cost_per_kg
0   Wheat      3200          4200     18000        64000     5.625000
1    Rice      2800          5500     20000        56000     7.142857
2   Maize      3500          3800     17000        70000     4.857143
3  Millet      3000          3000     15000        60000     5.000000

In [12]:
df["Yield_kg"].mode()

0    2800
1    3000
2    3200
3    3500
Name: Yield_kg, dtype: int64

In [13]:
df["Yield_kg"].median()

3100.0