In [1]:
import pandas as pd
import numpy as np
farm_data = {
"Crop": ["Wheat", "Rice", "Maize", "Millet", "Pulses"],
"Yield_kg": [3200, np.nan, 3500, 3000, np.nan],
"Water_liters": [4200, 5500, np.nan, 3000, 2500],
"Cost_INR": [18000, 20000, 17000, np.nan, 12000]
}
df = pd.DataFrame(farm_data)
df

     Crop  Yield_kg  Water_liters  Cost_INR
0   Wheat    3200.0        4200.0   18000.0
1    Rice       NaN        5500.0   20000.0
2   Maize    3500.0           NaN   17000.0
3  Millet    3000.0        3000.0       NaN
4  Pulses       NaN        2500.0   12000.0

In [2]:
df.isnull()

    Crop  Yield_kg  Water_liters  Cost_INR
0  False     False         False     False
1  False      True         False     False
2  False     False          True     False
3  False     False         False      True
4  False      True         False     False

In [3]:
df.isnull().sum()

Crop            0
Yield_kg        2
Water_liters    1
Cost_INR        1
dtype: int64

In [4]:
df.dropna()

    Crop  Yield_kg  Water_liters  Cost_INR
0  Wheat    3200.0        4200.0   18000.0

In [5]:
df["Yield_kg"].fillna(df["Yield_kg"].mean(), inplace=True)
df

/tmp/ipython-input-366998557.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Yield_kg"].fillna(df["Yield_kg"].mean(), inplace=True)

     Crop     Yield_kg  Water_liters  Cost_INR
0   Wheat  3200.000000        4200.0   18000.0
1    Rice  3233.333333        5500.0   20000.0
2   Maize  3500.000000           NaN   17000.0
3  Millet  3000.000000        3000.0       NaN
4  Pulses  3233.333333        2500.0   12000.0

In [6]:
df.fillna(method="ffill", inplace=True)
df

/tmp/ipython-input-2541247499.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", inplace=True)

     Crop     Yield_kg  Water_liters  Cost_INR
0   Wheat  3200.000000        4200.0   18000.0
1    Rice  3233.333333        5500.0   20000.0
2   Maize  3500.000000        5500.0   17000.0
3  Millet  3000.000000        3000.0   17000.0
4  Pulses  3233.333333        2500.0   12000.0

In [7]:
df.fillna(method="bfill", inplace=True)
df

/tmp/ipython-input-3840312381.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill", inplace=True)

     Crop     Yield_kg  Water_liters  Cost_INR
0   Wheat  3200.000000        4200.0   18000.0
1    Rice  3233.333333        5500.0   20000.0
2   Maize  3500.000000        5500.0   17000.0
3  Millet  3000.000000        3000.0   17000.0
4  Pulses  3233.333333        2500.0   12000.0